# Generated by Django 2.1 on 2020-02-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='track',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
